name: Pull Request

on: [pull_request]

jobs:
  config:
    uses: klever-io/workflow-calls/.github/workflows/go-setup.yaml@master
    with:
      with_vendor: false
      with_cache: false
      go_private: "github.com/klever-io/*"
    secrets:
      git_user: ${{ secrets.GIT_USER }}
      git_pass: ${{ secrets.GIT_PASS }}

  build:
    needs: [config]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: cache vendored dependencies
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ hashFiles('**/go.sum') }}-${{ secrets.CACHE_VERSION }}

      - name: GoImports Formatter
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go mod tidy
          goimports -w -d $(find . -type f -name '*.go' -not -name '*.pb.go' -not -name '*_setter.go' -not -path "./vendor/*")

      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi

      - name: vendor dependencies
        run: |
          go mod vendor
          go install github.com/goware/modvendor@latest
          modvendor -copy="**/*.c **/*.h **/*.proto **/*.a" -v
        if: steps.cache-vendor.outputs.cache-hit != 'true'

      - name: ensure code is buildable
        run: |
          go vet ./...

      - name: ensure all test is passing
        run: |
          go clean -testcache
          go test ./...
