name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  ensure-code:
    uses: klever-io/workflow-calls/.github/workflows/go-ci.yaml@master
    secrets:
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      twingate_sa: ${{ secrets.TWINGATE_SERVICE_ACCOUNT }}